apiVersion: v1
kind: Pod
metadata:
  name: jnlp
spec:
  containers:
  - name: shell
    image: ubuntu
    command: 
    - cat
    tty: true 
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: git
    image: alpine/git
    command:
    - /bin/cat
    tty: true 
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true    
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock