apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
   argocd-image-updater.argoproj.io/image-list: 'testing=docker.io/tarmizy/test:latest'   #Write repository name
   argocd-image-updater.argoproj.io/testing.update-strategy: 'digest' #There are several ways to update the image, but I'm using digest
  #  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
   argocd-image-updater.argoproj.io/git-branch: 'main'
   argocd-image-updater.argoproj.io/testing.force-update: 'true'
   argocd-image-updater.argoproj.io/write-back-method: 'git:secret:argocd/git-credential'
  name: 'testing-app'
  namespace: 'argocd'
spec:
  destination:
    namespace: 'testing'
    server: 'https://kubernetes.default.svc' 
  source:
    path: 'demo'
    repoURL: 'https://github.com/tarmizy/demo-manifest.git'
    targetRevision: HEAD
  sources: []
  project: 'default'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true